# Generated by Django 4.2.7 on 2025-09-06 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the task', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the task', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', help_text='Current status of the task', max_length=20)),
                ('due_date', models.DateTimeField(blank=True, help_text='Due date and time for the task', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the task was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the task was last updated')),
                ('user', models.ForeignKey(help_text='User who owns this task', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='tasks_task_user_id_c0fce1_idx'), models.Index(fields=['due_date'], name='tasks_task_due_dat_bce847_idx')],
            },
        ),
    ]
